apiVersion: v1
kind: Service
metadata:
  name: neo4j-cluster
  labels:
    app: neo4j-cluster
spec:
  selector:
    app: neo4j-cluster
  ports:
    - name: tcp-bolt
      port: 7687
      protocol: TCP
      targetPort: 7687
    - name: tcp-http
      port: 7474
      protocol: TCP
      targetPort: 7474
    - name: tcp-https
      port: 7473
      protocol: TCP
      targetPort: 7473
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-cluster-internal
spec:
  selector:
    app: neo4j-cluster
  ports:
    - name: tcp-backup
      port: 6362
      protocol: TCP
      targetPort: 6362
    - name: tcp-bolt
      port: 7687
      protocol: TCP
      targetPort: 7687
    - name: tcp-http
      port: 7474
      protocol: TCP
      targetPort: 7474
    - name: tcp-https
      port: 7473
      protocol: TCP
      targetPort: 7473
    - name: tcp-boltrouting
      port: 7688
      protocol: TCP
      targetPort: 7688
    - name: tcp-raft
      port: 7000
      protocol: TCP
      targetPort: 7000
    - name: tcp-tx
      port: 6000
      protocol: TCP
      targetPort: 6000
  clusterIP: None
  publishNotReadyAddresses: true
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-cluster-discovery
spec:
  selector:
    app: neo4j-cluster
  ports:
    - name: discovery
      port: 5000
      protocol: TCP
      targetPort: 5000
  clusterIP: None
  publishNotReadyAddresses: true

