apiVersion: v1
kind: ConfigMap

metadata:
  name: cluster-default-config
data:
  server.directories.data: "/data"
  server.directories.plugins: "/plugins"
  server.directories.logs: "/logs"
  server.directories.licenses: "/licenses"
  server.directories.metrics: "/metrics"
  server.directories.import: "/import"
  server.default_listen_address: "0.0.0.0"
  server.default_advertised_address: "$(bash -c 'echo ${SERVICE_NEO4J}')"
  server.bolt.advertised_address: "$(bash -c 'echo ${POD_IP//./-}.${SERVICE_NEO4J_INTERNALS}:7687)"
  server.discovery.advertised_address: "$(bash -c 'echo ${POD_IP//./-}.${SERVICE_NEO4J_DISCOVERY}:5000')"
  server.discovery.listen_address: "0.0.0.0:5000"
  dbms.cluster.discovery.type: SRV
  dbms.cluster.discovery.endpoints: "$(bash -c 'echo _discovery._tcp.${SERVICE_NEO4J_DISCOVERY}:0')"
  dbms.cluster.minimum_initial_system_primaries_count: "3"
  initial.dbms.default_primaries_count: "3"
  initial.dbms.default_secondaries_count: "1"
  dbms.security.cluster_status_auth_enabled: "false"
  server.cluster.advertised_address: "$(bash -c 'echo ${POD_IP//./-}.${SERVICE_NEO4J_INTERNALS}:6000')"
  server.cluster.listen_address: "0.0.0.0:6000"
  server.cluster.raft.advertised_address: "$(bash -c 'echo ${POD_IP//./-}.${SERVICE_NEO4J_INTERNALS}:7000')"
  server.cluster.raft.listen_address: "0.0.0.0:7000"
  server.routing.advertised_address: "$(bash -c 'echo ${POD_IP//./-}.${SERVICE_NEO4J_INTERNALS}:7688')"
  server.routing.listen_address: "0.0.0.0:7688"
  server.groups: "$(bash -c 'echo pod-${POD_NAME},cores')"
  dbms.routing.enabled: "true"
  dbms.routing.default_router: "SERVER"
  dbms.routing.client_side.enforce_for_domains: "*.cluster.local"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-env
data:
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_EDITION: "ENTERPRISE_K8S"
  NEO4J_CONF: "/config/"
  K8S_NEO4J_NAME: "neo4j-cluster"
  EXTENDED_CONF: "yes"
